//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPNETWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOPNETWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string cwBtnNo {
            get {
                return ResourceManager.GetString("cwBtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string cwBtnYes {
            get {
                return ResourceManager.GetString("cwBtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string cwText {
            get {
                return ResourceManager.GetString("cwText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string cwTitle {
            get {
                return ResourceManager.GetString("cwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away team.
        /// </summary>
        public static string lblAwayTeam {
            get {
                return ResourceManager.GetString("lblAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string lblChampionship {
            get {
                return ResourceManager.GetString("lblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played games/wins/loses.
        /// </summary>
        public static string lblGames {
            get {
                return ResourceManager.GetString("lblGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored/received goals/difference.
        /// </summary>
        public static string lblGoalStats {
            get {
                return ResourceManager.GetString("lblGoalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home team.
        /// </summary>
        public static string lblHomeTeam {
            get {
                return ResourceManager.GetString("lblHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. of goals.
        /// </summary>
        public static string lblNumOfGoals {
            get {
                return ResourceManager.GetString("lblNumOfGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string lblNumOfYellows {
            get {
                return ResourceManager.GetString("lblNumOfYellows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number.
        /// </summary>
        public static string lblShirtNumber {
            get {
                return ResourceManager.GetString("lblShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsTittle {
            get {
                return ResourceManager.GetString("settingsTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string titlePlayerDetails {
            get {
                return ResourceManager.GetString("titlePlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team details.
        /// </summary>
        public static string titleTeamDetails {
            get {
                return ResourceManager.GetString("titleTeamDetails", resourceCulture);
            }
        }
    }
}
